### PR TITLE
patch: improvements for Staking Mobile layouts

### PR DESCRIPTION
**Pull request by venumasini777**
Staking Mobile Tables Earlier:
Screenshot 2024-03-04 at 6 11 22 PM
Screenshot 2024-03-04 at 6 11 29 PM

After the changes: (majorly left aligned for columns on mobile)
Screenshot 2024-03-04 at 6 11 49 PM
Screenshot 2024-03-04 at 6 11 58 PM

### CODE REVIEW

**Comment by waajito** [comment]
@venumasini777 Images for the changes

**Comment by venumasini777** [comment]
> @venumasini777 Images for the changes

Added the images

**Review by dsudit01 — APPROVED** [review]
LGTM

**Comment by venumasini777** [comment]
Yep, done the changes @dsudit01 modified the code a bit to include time for mobile and adjust the width as well

**Pull request merged**
