### PR TITLE
feat : integrate vivacity lending market

### PR DESCRIPTION
**Pull request by sairamplex**
Add hooks for fetching note amount supplied and rewards from vivacity lending market
Add tx flow and functions to supply/withdraw note 
Add tx flow flow and function to claim rewards from vivacity

### CODE REVIEW

**Review by dsudit01 — APPROVED** [review]
LGTM. Vivacity tokens are never used in the page for Lending. Will need to add a table for these

**Comment by tkkwon1998** [comment]
> LGTM. Vivacity tokens are never used in the page for Lending. Will need to add a table for these

sweet. the new lending redesign made by @waajito will need to integrate these hooks

**Comment by waajito** [comment]
new lending is branched off of main. it will introduce a bunch of merge conflicts. I'll try to get the lending done once everything is finished. we can do the integration.

**Comment by dsudit01** [comment]
we will make a feature branch for this

**Pull request closed without merging**
